import "~/styles/globals.css";

import Next, { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import  TopNav  from  "./_components/topnav"
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";

import "@uploadthing/react/styles.css";
import { ourFileRouter } from "./api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";

export const metadata: Metadata = {
  title: "Chirp Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});




export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider dynamic >
    <html lang="en" className={`${geist.variable}`}>
    <NextSSRPlugin
          
            routerConfig={extractRouterConfig(ourFileRouter)}
          />
      <body> <TopNav/>{children}</body>
    </html>
    </ClerkProvider>
  );
}
